DROP TABLE IF EXISTS weibo_user;

CREATE TABLE weibo_user (
	id BIGINT NOT NULL,
	screen_name NVARCHAR(128) NOT NULL,
	name NVARCHAR(128) NOT NULL,
	province VARCHAR(16) DEFAULT NULL,
	city VARCHAR(16) DEFAULT NULL,
	location NVARCHAR(128) DEFAULT NULL,
	description TEXT,
	url NVARCHAR(128) NOT NULL,
	profile_image_url VARCHAR(128) DEFAULT NULL,
	domain VARCHAR(128) DEFAULT NULL,  
	gender VARCHAR(4) DEFAULT NULL,
	followers_count INT(16) DEFAULT NULL,
	friends_count INT(16) DEFAULT NULL,
	statuses_count INT(16) DEFAULT NULL,
	favourites_count INT(16) DEFAULT NULL,
	created_at VARCHAR(64) DEFAULT NULL,
	following TINYINT DEFAULT NULL,
	allow_all_act_msg TINYINT DEFAULT NULL,
	remark TEXT,
	geo_enabled TINYINT DEFAULT NULL,
	verified TINYINT DEFAULT NULL,
	allow_all_comment TINYINT DEFAULT NULL,
	avatar_large VARCHAR(128) DEFAULT NULL,
	verified_reason TEXT,
	follow_me TINYINT DEFAULT NULL,
	online_status INT(16) DEFAULT NULL,
	bi_followers_count INT(16) DEFAULT NULL,
	created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE KEY (screen_name),
	UNIQUE KEY (url),
	INDEX INX_WEIBO_USER_NAME (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;