DROP TABLE IF EXISTS weibo_comment;

CREATE TABLE weibo_comment (
	id BIGINT NOT NULL,
	user_id BIGINT NOT NULL,
	post_id BIGINT NOT NULL,
	text TEXT,
	source NVARCHAR(128) NOT NULL,
	mid VARCHAR(64) NOT NULL,
	created_at DATETIME NOT NULL,
	created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	/*FOREIGN KEY FK_WEIBO_COMMENT_USER_ID (user_id) REFERENCES weibo_user(id),
	FOREIGN KEY FK_WEIBO_COMMENT_POST_ID (post_id) REFERENCES weibo_post(id),
	*/
	UNIQUE KEY (mid),
	INDEX INX_WEIBO_COMMENT_CREATED_AT (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;